module.exports = {
  content: ["./*.html", "./camz/*.html"],
  theme: {
    fontFamily: {
      originalSurfer: ["Original Surfer", "sans-serif"],
    },
    extend: {},
  },
  safelist: [
    "backdrop-blur-md",
    "backdrop-blur-lg",
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-3",
    "grid-cols-4",
    "grid-cols-5",
    "grid-cols-6",
    "max-w-full",
    "bg-right",
    "bg-white/5",
    "text-white/80",
    "mt-0.5",
    "mt-1",
    "border-t",
    "border-white/10",
    "py-2",
    "max-h-12",
    "bottom-0",
    "left-0",
    "right-0",
    "flex",
    "flex-col",
    "bg-black/50",
    "text-sm",
    "z-20",
    "opacity-0",
    "group-hover:opacity-100",
    "transition-opacity",
    "duration-300",
    "group",
  ],
  daisyui: {
    themes: ["light", "dark", "cupcake"],
  },
  plugins: [require("daisyui")],
};
